version: '3.8'

services:
  mongodb:
    image: mongo
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  server:
    #build: ./SERVER
    image: ghcr.io/aziz4785/smartstyle-server:v0.1
    volumes:
      - ./SERVER:/server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  test:
    #build: ./SERVER
    image: ghcr.io/aziz4785/smartstyle-test:v0.1
    volumes:
      - ./SERVER:/server
    command: ["sh", "-c", "python -m unittest /server/tests/test_embedding_catalog1.py"]
    depends_on:
      - mongodb
    networks:
      - mynetwork

volumes:
  mongodb_data:

networks:
  mynetwork: