version: '3.8'

services:
  mongodb:
    image: mongo
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok ? quit(0) : quit(1)"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  server:
    build: ./SERVER
    #image: ghcr.io/aziz4785/smartstyle-server:v0.1
    volumes:
      - ./SERVER:/server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./SERVER/static:/usr/share/nginx/html/static
      - ./SERVER/templates:/usr/share/nginx/html/templates
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - mynetwork
volumes:
  mongodb_data:

networks:
  mynetwork: