import unittest
from metadata_generator import OtherColorClassifier, OpenAIClient  # Replace 'your_module' with the actual module name

def classify_othercolor(description):
    api_client = OpenAIClient()  # Assuming this sets up the API client correctly
    classifier = OtherColorClassifier(api_client)
    return classifier.classify(description)

class TestGarmentOtherColorClassification(unittest.TestCase):
    def test_classification(self):
        test_cases = [("Khaki\n\nThis pair of Jack & Jones Chino pants exhibits a solid khaki color. They are designed with a sleek and modern fit that appears to be neither too tight nor too loose, ensuring versatility for various occasions. The chinos feature a classic button and zip closure, with belt loops around the waist for accessorizing with a belt. There are side pockets at the hips and additional welt pockets at the back, which are typical characteristics of chino-style trousers. The hem of the pants is neatly finished, and the fabric lays smoothly over the shoes, showcasing a clean and casual look. There is no visible graphics or text on these pants; they maintain a simple yet sophisticated aesthetics.","yes"),
                      ("The DeFacto Slim Fit Pullover is presented in a solid burgundy color. It features a minimalistic, clean design with a high, close-fitting turtleneck that provides both warmth and style. The pullover has a body-hugging slim fit cut that accentuates the body shape, and it appears to have long sleeves with ribbed cuffs. Similarly, the bottom hem of the pullover is also ribbed, promoting a snug fit with added elasticity around the waist. There are no visible graphics, patterns, or text on the garment; its aesthetic is defined by its sleek and straightforward appearance. Overall, the garment exudes a sophisticated and contemporary vibe suitable for various casual and semi-formal occasions.","yes"),
                      ("White, black\n\nThe Lacoste T-CLIP - Baskets basses are a classic low-cut sneaker design featuring a harmonious blend of white and black colors. The upper includes black leather accents strategically placed at the toe, lace guard, and heel, combined with large white panels on the sides and top, creating a refined contrast. A prominent, stylized crocodile logo is featured on the side, typical of the brand's iconic branding. The shoe has a round toe shape and utilizes lacing for closure, providing a secure and adjustable fit. The sole shows a streamlined black and white profile that complements the upper's color palette, and additional branding appears on the heel where the brand's name is displayed in black lettering on a white patch.","no"),
                      ("Tan, dark blue, white, gray, yellow.\n\nThe Timberland SPRINT TREKKER boots feature a tan nubuck/textile upper with a dark blue padded collar. The outsole is a contrasting white with gray accents. Yellow lacing adds a pop of color, secured by metal hooks that ensure durability and ease of fastening. The design includes a round toe cap and a flat heel shape, catering to both comfort and functionality. The prominent Timberland logo is visible on the side of the heel counter and on the tongue, giving it a recognizable brand identity. The boots convey a rugged yet stylish aesthetic, suitable for outdoor activities as well as casual wear.","yes"),
                      ("Beige, Heather\n\nThe Stradivarius SOFT-TOUCH Manteau classique is a long beige coat with a heather pattern. It features a structured design with a prominent lapel collar and a double-breasted front closure accented by buttons. The coat is tailored with flap pockets, adding practicality to its elegant appearance. The entirety of the garment showcases a minimalist and sophisticated style typical of classic outerwear, exuding an air of timeless fashion. There are no visible graphics or text on the coat, emphasizing its clean and chic aesthetic.","yes"),
                      ("Black\n\nThe Claudie Pierlot cape is a chic, black outerwear piece with a solid color pattern. It features elegant, minimalistic design elements consistent with a refined aesthetic. The cape has a turtleneck collar and an unlined construction, providing a sleek, flowy silhouette. The front view reveals a single visible fastening at the neck, which creates a clean line down the front, and the hem reaches approximately mid-thigh or knee length, depending on the wearer's height. Overall, the cape has a structured yet relaxed appearance, exuding effortless style. There are no visible graphics or text.","no"),
                      ("White, black, gold\n\nThe Puma CAVEN UNISEX - Baskets basses are low-top sneakers with a predominantly white upper featuring black and gold accents. The side showcases a signature Puma formstrip in black, while the branding includes a gold Puma logo on the tongue and additional gold text along the laces. They have a round shoe toe, a flat heel shape, and are closed by lacing over a flower-like toe design. The outsole appears to be a textured abrasion-resistant rubber for durability and grip. These sneakers exude a classic, sporty aesthetic that is versatile for various styles and occasions.","yes"),
                      ("Color: Black\n\nThe PULL&BEAR MOM jeans present a classic black color with a solid pattern, crafted from denim. These high-waisted jeans feature a tapered fit that gives a snug silhouette while still offering room through the hip and thigh. The closure is a traditional zip fly with a button on top. The jeans have five pockets: two in the back, two in the front with a smaller coin pocket inset in the right front pocket. They demonstrate a minimalist design with no visible graphics or text, focusing on a sleek and straightforward aesthetic suitable for versatile styling. The images show the jeans as a foundational piece that could be easily integrated into various outfits.","no"),
                      ("The Pier One Pullover features a color block design with shades of black, gray, and white. It incorporates a heathered pattern throughout, which gives it a textured appearance. The round collar is subtly outlined with a ribbed, solid black trim, offering a clean finish. Its cuffs and hem also have ribbed detailing for a snug fit, emphasizing the pullover's casual yet stylish look. There are no visible graphics or text on the garment. Overall, it presents a contemporary and versatile style suitable for various casual looks.","yes"),
                      ("Black\n\nThe Even&Odd cropped jumper is a solid black pullover featuring a ribbed texture. It has a round collar and a cropped silhouette that creates a contemporary and easy-to-style piece. Its design includes long sleeves that contribute to a relaxed, slightly oversized look, suitable for casual wear. There are no graphics or text visible, emphasizing its minimalist and versatile appeal.","no")
                        ]

        for description, expected in test_cases:
            with self.subTest(description=description):
                print("for "+description[:20])
                
                result = classify_othercolor(description)
                print("actual answer is :"+result)
                print("expected = "+expected)
                print()
                self.assertEqual(result, expected)

if __name__ == '__main__':
    unittest.main()